### ISSUE TITLE
Error: Unable to read save directory

### ISSUE THREAD

**Issue by xgobblez** [untamed0/Untamed-Now-Playing#16]
Error: Unable to read save directory.

Chrome can limit readable/writable directories, if you run into problems, try changing the folder to your 'My Documents' or a subdirectory of that folder eg: 'C:\Users\Sam\Documents\unp\'

Saving to my documents... but keep getting this error :(

**Comment by untamed0** [comment]
Hey xgobblez,

Please could you paste me the exact setting, including any forward/back slashes?

Thanks!

**Comment by untamed0** [comment]
Hey xgobblez,

I'm going to close this issue for now, if you're still encountering this problem or any other problems, please feel free to either reply to this ticket or create a new one.

Cheers.
