### ISSUE TITLE
Requesting Compatibility with NightBot.tv

### ISSUE THREAD

**Issue by swak** [untamed0/Untamed-Now-Playing#18]
NightBot.tv has an AutoDJ function that plays YouTube videos in a browser. If you could add compatibility to your plugin to write these names to a file and allow nightbot.tv dj to be used with Untamed.

**Comment by galenbrazell** [comment]
I'm also hoping for this, as I'd much prefer to use your extension for other music sites as well as while taking nightbot song requests. Thanks!

**Comment by untamed0** [comment]
Thank you both for the feedback, support will be added in the next version, eta is this week.
