### ISSUE TITLE
Chrome crashes on exit

### ISSUE THREAD

**Issue by tuimz** [untamed0/Untamed-Now-Playing#25]
When you exit chrome, the application crashes if you are listening to any music station. I will try to debug and fix it but making this issue anyway to notify you.

**Comment by untamed0** [comment]
I haven't been able to reproduce this, tried grooveshark, pandora, slacker & youtube. Chrome v27.0.1453.110 m.

Do you have album art downloading enabled?

**Comment by tuimz** [comment]
I dont have album art downloading enabled I think. I will check to make sure.

Steps to reproduce:
1. Play music on distortionradio.com (Im not sure yet if others have this too)
2. Close Chrome.

**Comment by untamed0** [comment]
Can't reproduce on distortionradio.com either, however there was another report of this happening (#13), which was fixed after disabling/enabling all other extensions. Chrome version in that case was 25.0.1364.172.

Please could you see if the crash occurs on youtube.com, where setInterval() isn't used?

**Comment by tuimz** [comment]
Seems to crash on youtube aswell.
Using: Google Chrome 27.0.1453.94 (Official Build 201630) m

**Comment by untamed0** [comment]
Sorry for the delay, please could you try again with the latest commit (4baef63c61d3a5b2264c72d159f32f079ba1e77f) ? I've switched to a different NPAPI plugin which should be more stable.

**Comment by tuimz** [comment]
Yes, this seems to have fixed it for me!

Cheers.
-Tim
