### ISSUE TITLE
Error: Unable to read save directory

### ISSUE THREAD

**Issue by thechibachi** [untamed0/Untamed-Now-Playing#3]

**Comment by untamed0** [comment]
Hi thechibachi, It seems Chrome imposes restrictions on what directories plugins can access, so far I've only encountered this problem when trying to save to directories outside of the users home directory (C:/Users/Username), what directory are you trying to save to?

Also I'll update the error message in the next version to explain this restriction.

Thanks.

**Comment by thechibachi** [comment]
2012/12/10 Sam notifications@github.com

> Hi thechibachi, It seems Chrome imposes restrictions on what directories
> plugins can access, so far I've only encountered this problem when trying
> to save to directories outside of the users home directory
> (C:/Users/Username), what directory are you trying to save to?
> 
> Also I'll update the error message in the next version to explain this
> restriction.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/untamed0/Untamed-Now-Playing/issues/3#issuecomment-11216009.
> 
> Hello

Ehhh... Its realy hard to say but this issues was just mine mistake. At the
begin in UNP options i wanted to save notepad file. And always when i
wanted to save i had that error so i decided to inform You about that
"bug". Some days after i wrote that issue I tried to save that in folder
and it worked. Later i tried to delete issue on github.com but i couldnt do
that.Now when i writing this i am feeling like dumb boy. So my apologies
for You, for wasted your time to read and to reply on that msg, and sorry
for my english. i am quite young and i didnt want to use google translator.
And one mmore time sorry. i hope UNP will grow up, and thanks to You for
did Very good job by create that great program.

Greeting from Poland and Good Luck!

**Comment by untamed0** [comment]
No problem at all, and your English isn't bad :). I'm glad you're finding UNP useful, If you have anymore problems or suggestions, feel free to create another issue.

Thanks again.
