### ISSUE TITLE
8tracks.com adding info multiple times

### ISSUE THREAD

**Issue by mikekthx** [untamed0/Untamed-Now-Playing#34]
Using [this commit](https://github.com/untamed0/Untamed-Now-Playing/commit/c7b606d84f8bdd68a7c9f319dc4e73c161cfbba1). Screeny of options enabled:
![untamed now playing v0 5 - options](https://f.cloud.github.com/assets/173126/726362/c5cad496-e0ee-11e2-9bdd-9b1b6427d586.png)

When streaming from an 8tracks.com playlist for the first time the songs are added twice.
e.g. "The StrokesThe Strokes - You Only Live OnceYou Only Live Once" in unp_now_playing.txt

Once the next song comes on the last one also remains.
e.g. "The StrokesYoung the GiantYoung the Giant - You Only Live OnceMy BodyMy Body" in unp_now_playing.txt

This keeps happening for each new song that plays until your maximum length is reached.

Files affected while using multiple text files are unp_artist_name.txt, unp_now_playing.txt, unp_album_name.txt, and unp_track_name.txt.

**Comment by untamed0** [comment]
Thanks for the report mikekthx :)

**Comment by mikekthx** [comment]
Fast fix :P Happy to help
