### ISSUE TITLE
Add support for http://seoul.fm/

### ISSUE THREAD

**Issue by Ychuang003** [untamed0/Untamed-Now-Playing#5]
I hope this website will be added to the support list.
Thanks in advance. :)

**Comment by untamed0** [comment]
Hey Ychuang003,

I had a quick look at seoul.fm for the last release, the site is a bit awkward because it uses an iframe from a different domain, but I'll take a closer look for the next release, I'm sure I'll be able to come up with something :).

Thanks.

**Comment by Ychuang003** [comment]
Thanks a lot for the effort. Much appreciate.
