### ISSUE TITLE
Add support for radiorecord.ru

### ISSUE THREAD

**Issue by iDeaDe** [untamed0/Untamed-Now-Playing#61]
Please add support for [radiorecord.ru](http://www.radiorecord.ru) :)

**Comment by untamed0** [comment]
This project is dead due to Chrome's removal of NPAPI and my own time constraints, Wykks has revived it and ported to firefox with a ton of other improvements, you can find it here: https://github.com/Wykks/Untamed-Now-Playing-Next

**Comment by iDeaDe** [comment]
I need it for chrome :c

**Comment by untamed0** [comment]
Unfortunately writing to local files is no longer viable using a Chrome extension alone.
